// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"Order/internal/logic"
	"Order/internal/svc"
	"Order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) GetOrderInfoByOrderNum(ctx context.Context, in *order.OrderInfoReq) (*order.OrderInfoResp, error) {
	l := logic.NewGetOrderInfoByOrderNumLogic(ctx, s.svcCtx)
	return l.GetOrderInfoByOrderNum(in)
}

func (s *OrderServer) GetOrderStatusByOrderNum(ctx context.Context, in *order.OrderInfoReq) (*order.OrderInfoResp, error) {
	l := logic.NewGetOrderStatusByOrderNumLogic(ctx, s.svcCtx)
	return l.GetOrderStatusByOrderNum(in)
}

func (s *OrderServer) CreateOrderInfo(ctx context.Context, in *order.OrderInfoReq) (*order.Response, error) {
	l := logic.NewCreateOrderInfoLogic(ctx, s.svcCtx)
	return l.CreateOrderInfo(in)
}

func (s *OrderServer) UpdateOrderInfo(ctx context.Context, in *order.OrderInfoReq) (*order.Response, error) {
	l := logic.NewUpdateOrderInfoLogic(ctx, s.svcCtx)
	return l.UpdateOrderInfo(in)
}
