// Code generated by goctl. DO NOT EDIT!
// Source: action.proto

package server

import (
	"context"

	"Action/action"
	"Action/internal/logic"
	"Action/internal/svc"
)

type ActionServer struct {
	svcCtx *svc.ServiceContext
}

func NewActionServer(svcCtx *svc.ServiceContext) *ActionServer {
	return &ActionServer{
		svcCtx: svcCtx,
	}
}

// TrafficStatistic
func (s *ActionServer) GetAllTrafficStatistics(ctx context.Context, in *action.Request) (*action.TrafficStatisticsResp, error) {
	l := logic.NewGetAllTrafficStatisticsLogic(ctx, s.svcCtx)
	return l.GetAllTrafficStatistics(in)
}

func (s *ActionServer) GetTrafficStatisticByBookIdAndChapterNum(ctx context.Context, in *action.TrafficStatisticReq) (*action.TrafficStatisticResp, error) {
	l := logic.NewGetTrafficStatisticByBookIdAndChapterNumLogic(ctx, s.svcCtx)
	return l.GetTrafficStatisticByBookIdAndChapterNum(in)
}

func (s *ActionServer) CreateTrafficStatistic(ctx context.Context, in *action.TrafficStatisticReq) (*action.Response, error) {
	l := logic.NewCreateTrafficStatisticLogic(ctx, s.svcCtx)
	return l.CreateTrafficStatistic(in)
}

func (s *ActionServer) UpdateTrafficStatistic(ctx context.Context, in *action.TrafficStatisticReq) (*action.Response, error) {
	l := logic.NewUpdateTrafficStatisticLogic(ctx, s.svcCtx)
	return l.UpdateTrafficStatistic(in)
}

// Comments
func (s *ActionServer) GetCommentsByBookContentId(ctx context.Context, in *action.CommentReq) (*action.CommentsTreeResp, error) {
	l := logic.NewGetCommentsByBookContentIdLogic(ctx, s.svcCtx)
	return l.GetCommentsByBookContentId(in)
}

func (s *ActionServer) CreateComment(ctx context.Context, in *action.CommentReq) (*action.Response, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *ActionServer) UpdateComment(ctx context.Context, in *action.CommentReq) (*action.Response, error) {
	l := logic.NewUpdateCommentLogic(ctx, s.svcCtx)
	return l.UpdateComment(in)
}

func (s *ActionServer) DeleteComment(ctx context.Context, in *action.CommentReq) (*action.Response, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
