// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 int64    `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Year                 int64    `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month                int64    `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() int64 {
	if m != nil {
		return m.Ping
	}
	return 0
}

func (m *Request) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Request) GetMonth() int64 {
	if m != nil {
		return m.Month
	}
	return 0
}

type Reply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UsernameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameReq) Reset()         { *m = UsernameReq{} }
func (m *UsernameReq) String() string { return proto.CompactTextString(m) }
func (*UsernameReq) ProtoMessage()    {}
func (*UsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *UsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameReq.Unmarshal(m, b)
}
func (m *UsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameReq.Marshal(b, m, deterministic)
}
func (m *UsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameReq.Merge(m, src)
}
func (m *UsernameReq) XXX_Size() int {
	return xxx_messageInfo_UsernameReq.Size(m)
}
func (m *UsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameReq proto.InternalMessageInfo

func (m *UsernameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type BookBasicInfoReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	StorageUserId        int64    `protobuf:"varint,5,opt,name=storage_user_id,json=storageUserId,proto3" json:"storage_user_id,omitempty"`
	StorageTime          string   `protobuf:"bytes,6,opt,name=storage_time,json=storageTime,proto3" json:"storage_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookBasicInfoReply) Reset()         { *m = BookBasicInfoReply{} }
func (m *BookBasicInfoReply) String() string { return proto.CompactTextString(m) }
func (*BookBasicInfoReply) ProtoMessage()    {}
func (*BookBasicInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *BookBasicInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookBasicInfoReply.Unmarshal(m, b)
}
func (m *BookBasicInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookBasicInfoReply.Marshal(b, m, deterministic)
}
func (m *BookBasicInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookBasicInfoReply.Merge(m, src)
}
func (m *BookBasicInfoReply) XXX_Size() int {
	return xxx_messageInfo_BookBasicInfoReply.Size(m)
}
func (m *BookBasicInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BookBasicInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BookBasicInfoReply proto.InternalMessageInfo

func (m *BookBasicInfoReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookBasicInfoReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookBasicInfoReply) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookBasicInfoReply) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BookBasicInfoReply) GetStorageUserId() int64 {
	if m != nil {
		return m.StorageUserId
	}
	return 0
}

func (m *BookBasicInfoReply) GetStorageTime() string {
	if m != nil {
		return m.StorageTime
	}
	return ""
}

type BooksBasicInfoReply struct {
	BooksBasicInfo       []*BookBasicInfoReply `protobuf:"bytes,1,rep,name=booksBasicInfo,proto3" json:"booksBasicInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BooksBasicInfoReply) Reset()         { *m = BooksBasicInfoReply{} }
func (m *BooksBasicInfoReply) String() string { return proto.CompactTextString(m) }
func (*BooksBasicInfoReply) ProtoMessage()    {}
func (*BooksBasicInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *BooksBasicInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooksBasicInfoReply.Unmarshal(m, b)
}
func (m *BooksBasicInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooksBasicInfoReply.Marshal(b, m, deterministic)
}
func (m *BooksBasicInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooksBasicInfoReply.Merge(m, src)
}
func (m *BooksBasicInfoReply) XXX_Size() int {
	return xxx_messageInfo_BooksBasicInfoReply.Size(m)
}
func (m *BooksBasicInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BooksBasicInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BooksBasicInfoReply proto.InternalMessageInfo

func (m *BooksBasicInfoReply) GetBooksBasicInfo() []*BookBasicInfoReply {
	if m != nil {
		return m.BooksBasicInfo
	}
	return nil
}

type BookBasicInfoReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	StorageUserId        int64    `protobuf:"varint,5,opt,name=storage_user_id,json=storageUserId,proto3" json:"storage_user_id,omitempty"`
	StorageTime          string   `protobuf:"bytes,6,opt,name=storage_time,json=storageTime,proto3" json:"storage_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookBasicInfoReq) Reset()         { *m = BookBasicInfoReq{} }
func (m *BookBasicInfoReq) String() string { return proto.CompactTextString(m) }
func (*BookBasicInfoReq) ProtoMessage()    {}
func (*BookBasicInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *BookBasicInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookBasicInfoReq.Unmarshal(m, b)
}
func (m *BookBasicInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookBasicInfoReq.Marshal(b, m, deterministic)
}
func (m *BookBasicInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookBasicInfoReq.Merge(m, src)
}
func (m *BookBasicInfoReq) XXX_Size() int {
	return xxx_messageInfo_BookBasicInfoReq.Size(m)
}
func (m *BookBasicInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookBasicInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookBasicInfoReq proto.InternalMessageInfo

func (m *BookBasicInfoReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookBasicInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookBasicInfoReq) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookBasicInfoReq) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BookBasicInfoReq) GetStorageUserId() int64 {
	if m != nil {
		return m.StorageUserId
	}
	return 0
}

func (m *BookBasicInfoReq) GetStorageTime() string {
	if m != nil {
		return m.StorageTime
	}
	return ""
}

type BookContentReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterNum           int64    `protobuf:"varint,3,opt,name=chapter_num,json=chapterNum,proto3" json:"chapter_num,omitempty"`
	ChapterName          string   `protobuf:"bytes,4,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	ChapterContent       string   `protobuf:"bytes,5,opt,name=chapter_content,json=chapterContent,proto3" json:"chapter_content,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookContentReq) Reset()         { *m = BookContentReq{} }
func (m *BookContentReq) String() string { return proto.CompactTextString(m) }
func (*BookContentReq) ProtoMessage()    {}
func (*BookContentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{6}
}

func (m *BookContentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookContentReq.Unmarshal(m, b)
}
func (m *BookContentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookContentReq.Marshal(b, m, deterministic)
}
func (m *BookContentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookContentReq.Merge(m, src)
}
func (m *BookContentReq) XXX_Size() int {
	return xxx_messageInfo_BookContentReq.Size(m)
}
func (m *BookContentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookContentReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookContentReq proto.InternalMessageInfo

func (m *BookContentReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookContentReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BookContentReq) GetChapterNum() int64 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *BookContentReq) GetChapterName() string {
	if m != nil {
		return m.ChapterName
	}
	return ""
}

func (m *BookContentReq) GetChapterContent() string {
	if m != nil {
		return m.ChapterContent
	}
	return ""
}

func (m *BookContentReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type BookContentReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterNum           int64    `protobuf:"varint,3,opt,name=chapter_num,json=chapterNum,proto3" json:"chapter_num,omitempty"`
	ChapterName          string   `protobuf:"bytes,4,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	ChapterContent       string   `protobuf:"bytes,5,opt,name=chapter_content,json=chapterContent,proto3" json:"chapter_content,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookContentReply) Reset()         { *m = BookContentReply{} }
func (m *BookContentReply) String() string { return proto.CompactTextString(m) }
func (*BookContentReply) ProtoMessage()    {}
func (*BookContentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{7}
}

func (m *BookContentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookContentReply.Unmarshal(m, b)
}
func (m *BookContentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookContentReply.Marshal(b, m, deterministic)
}
func (m *BookContentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookContentReply.Merge(m, src)
}
func (m *BookContentReply) XXX_Size() int {
	return xxx_messageInfo_BookContentReply.Size(m)
}
func (m *BookContentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BookContentReply.DiscardUnknown(m)
}

var xxx_messageInfo_BookContentReply proto.InternalMessageInfo

func (m *BookContentReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookContentReply) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BookContentReply) GetChapterNum() int64 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *BookContentReply) GetChapterName() string {
	if m != nil {
		return m.ChapterName
	}
	return ""
}

func (m *BookContentReply) GetChapterContent() string {
	if m != nil {
		return m.ChapterContent
	}
	return ""
}

func (m *BookContentReply) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type BookContentsReply struct {
	BookContentsReply    []*BookContentReply `protobuf:"bytes,1,rep,name=book_contents_reply,json=bookContentsReply,proto3" json:"book_contents_reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BookContentsReply) Reset()         { *m = BookContentsReply{} }
func (m *BookContentsReply) String() string { return proto.CompactTextString(m) }
func (*BookContentsReply) ProtoMessage()    {}
func (*BookContentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{8}
}

func (m *BookContentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookContentsReply.Unmarshal(m, b)
}
func (m *BookContentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookContentsReply.Marshal(b, m, deterministic)
}
func (m *BookContentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookContentsReply.Merge(m, src)
}
func (m *BookContentsReply) XXX_Size() int {
	return xxx_messageInfo_BookContentsReply.Size(m)
}
func (m *BookContentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BookContentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_BookContentsReply proto.InternalMessageInfo

func (m *BookContentsReply) GetBookContentsReply() []*BookContentReply {
	if m != nil {
		return m.BookContentsReply
	}
	return nil
}

type BookInventoryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Inventory            int64    `protobuf:"varint,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInventoryReq) Reset()         { *m = BookInventoryReq{} }
func (m *BookInventoryReq) String() string { return proto.CompactTextString(m) }
func (*BookInventoryReq) ProtoMessage()    {}
func (*BookInventoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{9}
}

func (m *BookInventoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInventoryReq.Unmarshal(m, b)
}
func (m *BookInventoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInventoryReq.Marshal(b, m, deterministic)
}
func (m *BookInventoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInventoryReq.Merge(m, src)
}
func (m *BookInventoryReq) XXX_Size() int {
	return xxx_messageInfo_BookInventoryReq.Size(m)
}
func (m *BookInventoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInventoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookInventoryReq proto.InternalMessageInfo

func (m *BookInventoryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookInventoryReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BookInventoryReq) GetInventory() int64 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type BookInventoryResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Inventory            int64    `protobuf:"varint,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInventoryResp) Reset()         { *m = BookInventoryResp{} }
func (m *BookInventoryResp) String() string { return proto.CompactTextString(m) }
func (*BookInventoryResp) ProtoMessage()    {}
func (*BookInventoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{10}
}

func (m *BookInventoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInventoryResp.Unmarshal(m, b)
}
func (m *BookInventoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInventoryResp.Marshal(b, m, deterministic)
}
func (m *BookInventoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInventoryResp.Merge(m, src)
}
func (m *BookInventoryResp) XXX_Size() int {
	return xxx_messageInfo_BookInventoryResp.Size(m)
}
func (m *BookInventoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInventoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_BookInventoryResp proto.InternalMessageInfo

func (m *BookInventoryResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookInventoryResp) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BookInventoryResp) GetInventory() int64 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type BooksInventoryResp struct {
	BooksInventoryResp   []*BookInventoryResp `protobuf:"bytes,1,rep,name=books_inventory_resp,json=booksInventoryResp,proto3" json:"books_inventory_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BooksInventoryResp) Reset()         { *m = BooksInventoryResp{} }
func (m *BooksInventoryResp) String() string { return proto.CompactTextString(m) }
func (*BooksInventoryResp) ProtoMessage()    {}
func (*BooksInventoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{11}
}

func (m *BooksInventoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooksInventoryResp.Unmarshal(m, b)
}
func (m *BooksInventoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooksInventoryResp.Marshal(b, m, deterministic)
}
func (m *BooksInventoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooksInventoryResp.Merge(m, src)
}
func (m *BooksInventoryResp) XXX_Size() int {
	return xxx_messageInfo_BooksInventoryResp.Size(m)
}
func (m *BooksInventoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BooksInventoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_BooksInventoryResp proto.InternalMessageInfo

func (m *BooksInventoryResp) GetBooksInventoryResp() []*BookInventoryResp {
	if m != nil {
		return m.BooksInventoryResp
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "book.Request")
	proto.RegisterType((*Reply)(nil), "book.Reply")
	proto.RegisterType((*UsernameReq)(nil), "book.UsernameReq")
	proto.RegisterType((*BookBasicInfoReply)(nil), "book.BookBasicInfoReply")
	proto.RegisterType((*BooksBasicInfoReply)(nil), "book.BooksBasicInfoReply")
	proto.RegisterType((*BookBasicInfoReq)(nil), "book.BookBasicInfoReq")
	proto.RegisterType((*BookContentReq)(nil), "book.BookContentReq")
	proto.RegisterType((*BookContentReply)(nil), "book.BookContentReply")
	proto.RegisterType((*BookContentsReply)(nil), "book.BookContentsReply")
	proto.RegisterType((*BookInventoryReq)(nil), "book.BookInventoryReq")
	proto.RegisterType((*BookInventoryResp)(nil), "book.BookInventoryResp")
	proto.RegisterType((*BooksInventoryResp)(nil), "book.BooksInventoryResp")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0x4e, 0x4b, 0x29, 0xf4, 0x14, 0x8a, 0x9d, 0x36, 0xb0, 0xa0, 0x89, 0xb8, 0x17, 0x82, 0x37,
	0x24, 0x60, 0x42, 0x0c, 0x57, 0xd2, 0x2a, 0xd2, 0x04, 0x30, 0x59, 0x24, 0x44, 0xbc, 0xd8, 0x6c,
	0xd9, 0x11, 0x36, 0xed, 0xee, 0x6c, 0x77, 0xa7, 0x26, 0xfb, 0x54, 0xc6, 0xa7, 0x30, 0x3e, 0x84,
	0xef, 0x62, 0xe6, 0xcc, 0xec, 0x5f, 0x7f, 0x30, 0x6b, 0xbc, 0xd0, 0xbb, 0x9d, 0xd3, 0xf9, 0xbe,
	0x73, 0xbe, 0x6f, 0xce, 0x39, 0x29, 0x40, 0x9f, 0xb1, 0xc1, 0x9e, 0x1f, 0x30, 0xce, 0x48, 0x45,
	0x7c, 0xeb, 0xef, 0x60, 0xc9, 0xa0, 0xa3, 0x31, 0x0d, 0x39, 0x21, 0x50, 0xf1, 0x1d, 0xef, 0x4e,
	0x2b, 0x6d, 0x97, 0x76, 0x17, 0x0c, 0xfc, 0x16, 0xb1, 0x88, 0x5a, 0x81, 0x56, 0x96, 0x31, 0xf1,
	0x4d, 0xda, 0xb0, 0xe8, 0x32, 0x8f, 0xdf, 0x6b, 0x0b, 0x18, 0x94, 0x07, 0x7d, 0x1f, 0x16, 0x0d,
	0xea, 0x0f, 0x23, 0xd2, 0x80, 0x32, 0x1b, 0x20, 0xc9, 0xb2, 0x51, 0x66, 0x03, 0xa2, 0xc1, 0x92,
	0x4b, 0xc3, 0xd0, 0xba, 0xa3, 0xc8, 0x52, 0x33, 0xe2, 0xa3, 0xfe, 0x02, 0xea, 0x57, 0x21, 0x0d,
	0x3c, 0xcb, 0xa5, 0x06, 0x1d, 0x91, 0x2d, 0x58, 0x1e, 0xab, 0x23, 0xc2, 0x6b, 0x46, 0x72, 0xd6,
	0xbf, 0x95, 0x80, 0x74, 0x18, 0x1b, 0x74, 0xac, 0xd0, 0xb9, 0xed, 0x79, 0x9f, 0x59, 0x92, 0xcb,
	0xb1, 0x55, 0xc1, 0x65, 0xc7, 0x16, 0xe5, 0x22, 0x5c, 0x26, 0xc2, 0x6f, 0xb2, 0x0e, 0x55, 0x6b,
	0xcc, 0xef, 0x59, 0x80, 0xf5, 0xd6, 0x0c, 0x75, 0x12, 0x32, 0x1c, 0x57, 0x54, 0x55, 0xc1, 0xb0,
	0x3c, 0x90, 0xe7, 0xb0, 0x16, 0x72, 0x16, 0x58, 0x77, 0xd4, 0x14, 0xc9, 0x4d, 0xc7, 0xd6, 0x16,
	0x91, 0x7e, 0x55, 0x85, 0x45, 0xc5, 0x3d, 0x9b, 0x3c, 0x83, 0x95, 0xf8, 0x1e, 0x77, 0x5c, 0xaa,
	0x55, 0x91, 0xa4, 0xae, 0x62, 0x1f, 0x1c, 0x97, 0xea, 0xd7, 0xd0, 0x12, 0x25, 0x87, 0x13, 0x35,
	0xbf, 0x86, 0x46, 0x3f, 0x17, 0xd6, 0x4a, 0xdb, 0x0b, 0xbb, 0xf5, 0x03, 0x6d, 0x0f, 0x1f, 0x67,
	0x5a, 0xa5, 0x31, 0x71, 0x5f, 0xff, 0x5a, 0x82, 0x47, 0x13, 0xd7, 0x46, 0xff, 0xb6, 0x15, 0xdf,
	0x4b, 0xd0, 0x10, 0x15, 0x77, 0x99, 0xc7, 0xa9, 0xc7, 0x67, 0xd5, 0xbb, 0x01, 0x4b, 0x42, 0xa6,
	0xc8, 0x22, 0x9b, 0xad, 0x2a, 0x8e, 0x3d, 0x9b, 0x3c, 0x85, 0xfa, 0xed, 0xbd, 0xe5, 0x73, 0x1a,
	0x98, 0xde, 0xd8, 0x55, 0x4d, 0x07, 0x2a, 0x74, 0x31, 0x76, 0x45, 0xfe, 0xe4, 0x82, 0x50, 0x2c,
	0x45, 0xc4, 0xa0, 0x0b, 0x21, 0x7c, 0x07, 0xd6, 0xe2, 0x2b, 0xb7, 0xb2, 0x04, 0x94, 0x52, 0x33,
	0x1a, 0x2a, 0xac, 0x0a, 0xc3, 0x64, 0x01, 0xb5, 0x78, 0x4e, 0x0a, 0xc8, 0x10, 0x2a, 0xf9, 0xa1,
	0xbc, 0x4f, 0x94, 0xcc, 0x6a, 0xc3, 0xff, 0x44, 0xcb, 0x27, 0x68, 0x66, 0xa4, 0x84, 0x52, 0xcb,
	0x09, 0xb4, 0xb0, 0x76, 0xc5, 0x1d, 0x9a, 0x81, 0x08, 0xab, 0x1e, 0x5d, 0x4f, 0x7b, 0x34, 0x6b,
	0x80, 0xd1, 0xec, 0x4f, 0xf2, 0xe8, 0x1f, 0xa5, 0x4f, 0x3d, 0xef, 0x0b, 0xf5, 0x38, 0x0b, 0xa2,
	0x42, 0x6f, 0xfe, 0x04, 0x6a, 0x4e, 0x0c, 0x54, 0x2e, 0xa5, 0x01, 0xfd, 0x46, 0xd6, 0x9d, 0xa1,
	0x0e, 0xfd, 0xbf, 0xc5, 0x6d, 0xca, 0x3d, 0x13, 0xe6, 0xc9, 0x7b, 0xd0, 0xc6, 0x19, 0x34, 0x93,
	0x8b, 0x66, 0x40, 0x43, 0x5f, 0xb9, 0xb2, 0x91, 0xba, 0x92, 0x83, 0x19, 0xa4, 0x3f, 0x45, 0x75,
	0xf0, 0x73, 0x19, 0x2a, 0xe2, 0x26, 0x79, 0x0b, 0x9b, 0x27, 0x8e, 0x67, 0x1f, 0x0f, 0x87, 0x98,
	0xf0, 0x92, 0x05, 0x9c, 0xda, 0x9d, 0xe8, 0x5c, 0x6c, 0x53, 0xb2, 0x2a, 0x29, 0xd5, 0x6a, 0xde,
	0xda, 0x4c, 0x33, 0x4c, 0xae, 0x93, 0x57, 0xb0, 0x92, 0xa5, 0x29, 0x80, 0x3c, 0x85, 0x96, 0x40,
	0xca, 0x9f, 0xa2, 0x33, 0x67, 0x40, 0xb1, 0xbf, 0xd6, 0x67, 0xee, 0xa1, 0xd1, 0x43, 0x4c, 0xe7,
	0xa0, 0x65, 0x98, 0x2e, 0x73, 0xdb, 0xe1, 0x0f, 0xe8, 0xba, 0xb0, 0x26, 0xe8, 0xde, 0x7b, 0x14,
	0x51, 0xd1, 0x03, 0x2c, 0x73, 0x97, 0x26, 0xd9, 0x07, 0xe8, 0x62, 0xab, 0xa3, 0xd9, 0xf3, 0xf0,
	0xf5, 0xd8, 0x2d, 0x05, 0x79, 0x43, 0x87, 0xb4, 0x20, 0xe4, 0xca, 0xb7, 0x0b, 0x65, 0x39, 0x83,
	0xc7, 0x99, 0x07, 0x8b, 0x87, 0xa6, 0x13, 0x75, 0x64, 0x7b, 0xb6, 0x67, 0x8c, 0xd8, 0x68, 0x6b,
	0x63, 0x2a, 0xaa, 0xc6, 0xf5, 0x1a, 0x76, 0x32, 0x5e, 0xa9, 0xdf, 0x62, 0xb2, 0x63, 0xcf, 0xee,
	0xa6, 0xbb, 0x65, 0x36, 0xf3, 0x9c, 0x91, 0x26, 0x87, 0xd0, 0x4c, 0xfd, 0x8b, 0x57, 0xca, 0x6c,
	0x8a, 0x9c, 0xbc, 0x43, 0x68, 0xa6, 0x26, 0x16, 0xc3, 0xa5, 0x4e, 0x16, 0xc0, 0x9d, 0x42, 0x3b,
	0x63, 0x67, 0x32, 0x6b, 0xd9, 0xb7, 0xc8, 0xee, 0xa0, 0x6c, 0xc7, 0x4c, 0x0c, 0xf9, 0x99, 0x1c,
	0xc8, 0x1c, 0x22, 0x79, 0x96, 0x79, 0x74, 0xf3, 0x66, 0x9f, 0x1c, 0x41, 0x2b, 0xf5, 0xef, 0xf7,
	0x65, 0xe5, 0x34, 0x1d, 0x41, 0x2b, 0xf5, 0xa2, 0x18, 0xb6, 0x53, 0xbd, 0xc1, 0x3f, 0x76, 0xfd,
	0x2a, 0xfe, 0xcb, 0x7b, 0xf9, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xe5, 0x3e, 0x9d, 0xf3, 0x09,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookClient interface {
	//  book_basic_info
	FindAllBooksSortedByMonth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
	FindAllBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
	FindBooksByLikeName(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
	FindBooksByStorageUserId(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
	FindOneBookById(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BookBasicInfoReply, error)
	CreateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
	DeleteBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
	UpdateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
	//  book_content
	FindAllBookContentsByBookId(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentsReply, error)
	FindOneBookContentByBookIdAndChapterNum(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentReply, error)
	CreateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
	DeleteBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
	UpdateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
	// book_inventory
	FindAllBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BooksInventoryResp, error)
	FindBookInventoryByBookId(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BookInventoryResp, error)
	CreateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error)
	UpdateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) FindAllBooksSortedByMonth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	out := new(BooksBasicInfoReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindAllBooksSortedByMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindAllBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	out := new(BooksBasicInfoReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindAllBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindBooksByLikeName(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	out := new(BooksBasicInfoReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindBooksByLikeName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindBooksByStorageUserId(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	out := new(BooksBasicInfoReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindBooksByStorageUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindOneBookById(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BookBasicInfoReply, error) {
	out := new(BookBasicInfoReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindOneBookById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) CreateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) DeleteBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) UpdateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindAllBookContentsByBookId(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentsReply, error) {
	out := new(BookContentsReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindAllBookContentsByBookId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindOneBookContentByBookIdAndChapterNum(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentReply, error) {
	out := new(BookContentReply)
	err := c.cc.Invoke(ctx, "/book.Book/FindOneBookContentByBookIdAndChapterNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) CreateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/CreateBookContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) DeleteBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/DeleteBookContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) UpdateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/UpdateBookContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindAllBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BooksInventoryResp, error) {
	out := new(BooksInventoryResp)
	err := c.cc.Invoke(ctx, "/book.Book/FindAllBookInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) FindBookInventoryByBookId(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BookInventoryResp, error) {
	out := new(BookInventoryResp)
	err := c.cc.Invoke(ctx, "/book.Book/FindBookInventoryByBookId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) CreateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/CreateBookInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) UpdateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/book.Book/UpdateBookInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServer is the server API for Book service.
type BookServer interface {
	//  book_basic_info
	FindAllBooksSortedByMonth(context.Context, *Request) (*BooksBasicInfoReply, error)
	FindAllBooks(context.Context, *Request) (*BooksBasicInfoReply, error)
	FindBooksByLikeName(context.Context, *BookBasicInfoReq) (*BooksBasicInfoReply, error)
	FindBooksByStorageUserId(context.Context, *BookBasicInfoReq) (*BooksBasicInfoReply, error)
	FindOneBookById(context.Context, *BookBasicInfoReq) (*BookBasicInfoReply, error)
	CreateBook(context.Context, *BookBasicInfoReq) (*Reply, error)
	DeleteBook(context.Context, *BookBasicInfoReq) (*Reply, error)
	UpdateBook(context.Context, *BookBasicInfoReq) (*Reply, error)
	//  book_content
	FindAllBookContentsByBookId(context.Context, *BookContentReq) (*BookContentsReply, error)
	FindOneBookContentByBookIdAndChapterNum(context.Context, *BookContentReq) (*BookContentReply, error)
	CreateBookContent(context.Context, *BookContentReq) (*Reply, error)
	DeleteBookContent(context.Context, *BookContentReq) (*Reply, error)
	UpdateBookContent(context.Context, *BookContentReq) (*Reply, error)
	// book_inventory
	FindAllBookInventory(context.Context, *BookInventoryReq) (*BooksInventoryResp, error)
	FindBookInventoryByBookId(context.Context, *BookInventoryReq) (*BookInventoryResp, error)
	CreateBookInventory(context.Context, *BookInventoryReq) (*Reply, error)
	UpdateBookInventory(context.Context, *BookInventoryReq) (*Reply, error)
}

// UnimplementedBookServer can be embedded to have forward compatible implementations.
type UnimplementedBookServer struct {
}

func (*UnimplementedBookServer) FindAllBooksSortedByMonth(ctx context.Context, req *Request) (*BooksBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllBooksSortedByMonth not implemented")
}
func (*UnimplementedBookServer) FindAllBooks(ctx context.Context, req *Request) (*BooksBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllBooks not implemented")
}
func (*UnimplementedBookServer) FindBooksByLikeName(ctx context.Context, req *BookBasicInfoReq) (*BooksBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBooksByLikeName not implemented")
}
func (*UnimplementedBookServer) FindBooksByStorageUserId(ctx context.Context, req *BookBasicInfoReq) (*BooksBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBooksByStorageUserId not implemented")
}
func (*UnimplementedBookServer) FindOneBookById(ctx context.Context, req *BookBasicInfoReq) (*BookBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneBookById not implemented")
}
func (*UnimplementedBookServer) CreateBook(ctx context.Context, req *BookBasicInfoReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedBookServer) DeleteBook(ctx context.Context, req *BookBasicInfoReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (*UnimplementedBookServer) UpdateBook(ctx context.Context, req *BookBasicInfoReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedBookServer) FindAllBookContentsByBookId(ctx context.Context, req *BookContentReq) (*BookContentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllBookContentsByBookId not implemented")
}
func (*UnimplementedBookServer) FindOneBookContentByBookIdAndChapterNum(ctx context.Context, req *BookContentReq) (*BookContentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneBookContentByBookIdAndChapterNum not implemented")
}
func (*UnimplementedBookServer) CreateBookContent(ctx context.Context, req *BookContentReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBookContent not implemented")
}
func (*UnimplementedBookServer) DeleteBookContent(ctx context.Context, req *BookContentReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookContent not implemented")
}
func (*UnimplementedBookServer) UpdateBookContent(ctx context.Context, req *BookContentReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBookContent not implemented")
}
func (*UnimplementedBookServer) FindAllBookInventory(ctx context.Context, req *BookInventoryReq) (*BooksInventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllBookInventory not implemented")
}
func (*UnimplementedBookServer) FindBookInventoryByBookId(ctx context.Context, req *BookInventoryReq) (*BookInventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBookInventoryByBookId not implemented")
}
func (*UnimplementedBookServer) CreateBookInventory(ctx context.Context, req *BookInventoryReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBookInventory not implemented")
}
func (*UnimplementedBookServer) UpdateBookInventory(ctx context.Context, req *BookInventoryReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBookInventory not implemented")
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_FindAllBooksSortedByMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindAllBooksSortedByMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindAllBooksSortedByMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindAllBooksSortedByMonth(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindAllBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindAllBooks(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindBooksByLikeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindBooksByLikeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindBooksByLikeName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindBooksByLikeName(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindBooksByStorageUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindBooksByStorageUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindBooksByStorageUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindBooksByStorageUserId(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindOneBookById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindOneBookById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindOneBookById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindOneBookById(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).CreateBook(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).DeleteBook(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).UpdateBook(ctx, req.(*BookBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindAllBookContentsByBookId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindAllBookContentsByBookId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindAllBookContentsByBookId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindAllBookContentsByBookId(ctx, req.(*BookContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindOneBookContentByBookIdAndChapterNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindOneBookContentByBookIdAndChapterNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindOneBookContentByBookIdAndChapterNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindOneBookContentByBookIdAndChapterNum(ctx, req.(*BookContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_CreateBookContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).CreateBookContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/CreateBookContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).CreateBookContent(ctx, req.(*BookContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_DeleteBookContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).DeleteBookContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/DeleteBookContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).DeleteBookContent(ctx, req.(*BookContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_UpdateBookContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).UpdateBookContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/UpdateBookContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).UpdateBookContent(ctx, req.(*BookContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindAllBookInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindAllBookInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindAllBookInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindAllBookInventory(ctx, req.(*BookInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_FindBookInventoryByBookId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).FindBookInventoryByBookId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/FindBookInventoryByBookId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).FindBookInventoryByBookId(ctx, req.(*BookInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_CreateBookInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).CreateBookInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/CreateBookInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).CreateBookInventory(ctx, req.(*BookInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_UpdateBookInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).UpdateBookInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/UpdateBookInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).UpdateBookInventory(ctx, req.(*BookInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllBooksSortedByMonth",
			Handler:    _Book_FindAllBooksSortedByMonth_Handler,
		},
		{
			MethodName: "FindAllBooks",
			Handler:    _Book_FindAllBooks_Handler,
		},
		{
			MethodName: "FindBooksByLikeName",
			Handler:    _Book_FindBooksByLikeName_Handler,
		},
		{
			MethodName: "FindBooksByStorageUserId",
			Handler:    _Book_FindBooksByStorageUserId_Handler,
		},
		{
			MethodName: "FindOneBookById",
			Handler:    _Book_FindOneBookById_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _Book_CreateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Book_DeleteBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Book_UpdateBook_Handler,
		},
		{
			MethodName: "FindAllBookContentsByBookId",
			Handler:    _Book_FindAllBookContentsByBookId_Handler,
		},
		{
			MethodName: "FindOneBookContentByBookIdAndChapterNum",
			Handler:    _Book_FindOneBookContentByBookIdAndChapterNum_Handler,
		},
		{
			MethodName: "CreateBookContent",
			Handler:    _Book_CreateBookContent_Handler,
		},
		{
			MethodName: "DeleteBookContent",
			Handler:    _Book_DeleteBookContent_Handler,
		},
		{
			MethodName: "UpdateBookContent",
			Handler:    _Book_UpdateBookContent_Handler,
		},
		{
			MethodName: "FindAllBookInventory",
			Handler:    _Book_FindAllBookInventory_Handler,
		},
		{
			MethodName: "FindBookInventoryByBookId",
			Handler:    _Book_FindBookInventoryByBookId_Handler,
		},
		{
			MethodName: "CreateBookInventory",
			Handler:    _Book_CreateBookInventory_Handler,
		},
		{
			MethodName: "UpdateBookInventory",
			Handler:    _Book_UpdateBookInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
