// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action.proto

package action

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TrafficStatisticReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=BookId,proto3" json:"BookId,omitempty"`
	ChapterNum           int64    `protobuf:"varint,3,opt,name=ChapterNum,proto3" json:"ChapterNum,omitempty"`
	TrafficNumber        int64    `protobuf:"varint,4,opt,name=TrafficNumber,proto3" json:"TrafficNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficStatisticReq) Reset()         { *m = TrafficStatisticReq{} }
func (m *TrafficStatisticReq) String() string { return proto.CompactTextString(m) }
func (*TrafficStatisticReq) ProtoMessage()    {}
func (*TrafficStatisticReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{2}
}

func (m *TrafficStatisticReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStatisticReq.Unmarshal(m, b)
}
func (m *TrafficStatisticReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStatisticReq.Marshal(b, m, deterministic)
}
func (m *TrafficStatisticReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStatisticReq.Merge(m, src)
}
func (m *TrafficStatisticReq) XXX_Size() int {
	return xxx_messageInfo_TrafficStatisticReq.Size(m)
}
func (m *TrafficStatisticReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStatisticReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStatisticReq proto.InternalMessageInfo

func (m *TrafficStatisticReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrafficStatisticReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *TrafficStatisticReq) GetChapterNum() int64 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *TrafficStatisticReq) GetTrafficNumber() int64 {
	if m != nil {
		return m.TrafficNumber
	}
	return 0
}

type TrafficStatisticResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=BookId,proto3" json:"BookId,omitempty"`
	ChapterNum           int64    `protobuf:"varint,3,opt,name=ChapterNum,proto3" json:"ChapterNum,omitempty"`
	TrafficNumber        int64    `protobuf:"varint,4,opt,name=TrafficNumber,proto3" json:"TrafficNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficStatisticResp) Reset()         { *m = TrafficStatisticResp{} }
func (m *TrafficStatisticResp) String() string { return proto.CompactTextString(m) }
func (*TrafficStatisticResp) ProtoMessage()    {}
func (*TrafficStatisticResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{3}
}

func (m *TrafficStatisticResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStatisticResp.Unmarshal(m, b)
}
func (m *TrafficStatisticResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStatisticResp.Marshal(b, m, deterministic)
}
func (m *TrafficStatisticResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStatisticResp.Merge(m, src)
}
func (m *TrafficStatisticResp) XXX_Size() int {
	return xxx_messageInfo_TrafficStatisticResp.Size(m)
}
func (m *TrafficStatisticResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStatisticResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStatisticResp proto.InternalMessageInfo

func (m *TrafficStatisticResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrafficStatisticResp) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *TrafficStatisticResp) GetChapterNum() int64 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *TrafficStatisticResp) GetTrafficNumber() int64 {
	if m != nil {
		return m.TrafficNumber
	}
	return 0
}

type TrafficStatisticsResp struct {
	TrafficStatistics    []*TrafficStatisticResp `protobuf:"bytes,1,rep,name=TrafficStatistics,proto3" json:"TrafficStatistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TrafficStatisticsResp) Reset()         { *m = TrafficStatisticsResp{} }
func (m *TrafficStatisticsResp) String() string { return proto.CompactTextString(m) }
func (*TrafficStatisticsResp) ProtoMessage()    {}
func (*TrafficStatisticsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{4}
}

func (m *TrafficStatisticsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficStatisticsResp.Unmarshal(m, b)
}
func (m *TrafficStatisticsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficStatisticsResp.Marshal(b, m, deterministic)
}
func (m *TrafficStatisticsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficStatisticsResp.Merge(m, src)
}
func (m *TrafficStatisticsResp) XXX_Size() int {
	return xxx_messageInfo_TrafficStatisticsResp.Size(m)
}
func (m *TrafficStatisticsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficStatisticsResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficStatisticsResp proto.InternalMessageInfo

func (m *TrafficStatisticsResp) GetTrafficStatistics() []*TrafficStatisticResp {
	if m != nil {
		return m.TrafficStatistics
	}
	return nil
}

type CommentReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	BookContentId        int64    `protobuf:"varint,3,opt,name=BookContentId,proto3" json:"BookContentId,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	CommentByUserId      int64    `protobuf:"varint,5,opt,name=CommentByUserId,proto3" json:"CommentByUserId,omitempty"`
	CommentToUserId      int64    `protobuf:"varint,6,opt,name=CommentToUserId,proto3" json:"CommentToUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentReq) Reset()         { *m = CommentReq{} }
func (m *CommentReq) String() string { return proto.CompactTextString(m) }
func (*CommentReq) ProtoMessage()    {}
func (*CommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{5}
}

func (m *CommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentReq.Unmarshal(m, b)
}
func (m *CommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentReq.Marshal(b, m, deterministic)
}
func (m *CommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentReq.Merge(m, src)
}
func (m *CommentReq) XXX_Size() int {
	return xxx_messageInfo_CommentReq.Size(m)
}
func (m *CommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommentReq proto.InternalMessageInfo

func (m *CommentReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommentReq) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CommentReq) GetBookContentId() int64 {
	if m != nil {
		return m.BookContentId
	}
	return 0
}

func (m *CommentReq) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CommentReq) GetCommentByUserId() int64 {
	if m != nil {
		return m.CommentByUserId
	}
	return 0
}

func (m *CommentReq) GetCommentToUserId() int64 {
	if m != nil {
		return m.CommentToUserId
	}
	return 0
}

type CommentResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	BookContentId        int64    `protobuf:"varint,3,opt,name=BookContentId,proto3" json:"BookContentId,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	CommentByUserId      int64    `protobuf:"varint,5,opt,name=CommentByUserId,proto3" json:"CommentByUserId,omitempty"`
	CommentToUserId      int64    `protobuf:"varint,6,opt,name=CommentToUserId,proto3" json:"CommentToUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResp) Reset()         { *m = CommentResp{} }
func (m *CommentResp) String() string { return proto.CompactTextString(m) }
func (*CommentResp) ProtoMessage()    {}
func (*CommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{6}
}

func (m *CommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResp.Unmarshal(m, b)
}
func (m *CommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResp.Marshal(b, m, deterministic)
}
func (m *CommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResp.Merge(m, src)
}
func (m *CommentResp) XXX_Size() int {
	return xxx_messageInfo_CommentResp.Size(m)
}
func (m *CommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResp proto.InternalMessageInfo

func (m *CommentResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommentResp) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CommentResp) GetBookContentId() int64 {
	if m != nil {
		return m.BookContentId
	}
	return 0
}

func (m *CommentResp) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CommentResp) GetCommentByUserId() int64 {
	if m != nil {
		return m.CommentByUserId
	}
	return 0
}

func (m *CommentResp) GetCommentToUserId() int64 {
	if m != nil {
		return m.CommentToUserId
	}
	return 0
}

type CommentsNodeResp struct {
	Comments             *CommentResp        `protobuf:"bytes,1,opt,name=Comments,proto3" json:"Comments,omitempty"`
	CommentsNode         []*CommentsNodeResp `protobuf:"bytes,2,rep,name=CommentsNode,proto3" json:"CommentsNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CommentsNodeResp) Reset()         { *m = CommentsNodeResp{} }
func (m *CommentsNodeResp) String() string { return proto.CompactTextString(m) }
func (*CommentsNodeResp) ProtoMessage()    {}
func (*CommentsNodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{7}
}

func (m *CommentsNodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsNodeResp.Unmarshal(m, b)
}
func (m *CommentsNodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsNodeResp.Marshal(b, m, deterministic)
}
func (m *CommentsNodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsNodeResp.Merge(m, src)
}
func (m *CommentsNodeResp) XXX_Size() int {
	return xxx_messageInfo_CommentsNodeResp.Size(m)
}
func (m *CommentsNodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsNodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsNodeResp proto.InternalMessageInfo

func (m *CommentsNodeResp) GetComments() *CommentResp {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *CommentsNodeResp) GetCommentsNode() []*CommentsNodeResp {
	if m != nil {
		return m.CommentsNode
	}
	return nil
}

type CommentsTreeResp struct {
	CommentsTree         []*CommentsNodeResp `protobuf:"bytes,1,rep,name=CommentsTree,proto3" json:"CommentsTree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CommentsTreeResp) Reset()         { *m = CommentsTreeResp{} }
func (m *CommentsTreeResp) String() string { return proto.CompactTextString(m) }
func (*CommentsTreeResp) ProtoMessage()    {}
func (*CommentsTreeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59885c909ad4dfd3, []int{8}
}

func (m *CommentsTreeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsTreeResp.Unmarshal(m, b)
}
func (m *CommentsTreeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsTreeResp.Marshal(b, m, deterministic)
}
func (m *CommentsTreeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsTreeResp.Merge(m, src)
}
func (m *CommentsTreeResp) XXX_Size() int {
	return xxx_messageInfo_CommentsTreeResp.Size(m)
}
func (m *CommentsTreeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsTreeResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsTreeResp proto.InternalMessageInfo

func (m *CommentsTreeResp) GetCommentsTree() []*CommentsNodeResp {
	if m != nil {
		return m.CommentsTree
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "action.Request")
	proto.RegisterType((*Response)(nil), "action.Response")
	proto.RegisterType((*TrafficStatisticReq)(nil), "action.TrafficStatisticReq")
	proto.RegisterType((*TrafficStatisticResp)(nil), "action.TrafficStatisticResp")
	proto.RegisterType((*TrafficStatisticsResp)(nil), "action.TrafficStatisticsResp")
	proto.RegisterType((*CommentReq)(nil), "action.CommentReq")
	proto.RegisterType((*CommentResp)(nil), "action.CommentResp")
	proto.RegisterType((*CommentsNodeResp)(nil), "action.CommentsNodeResp")
	proto.RegisterType((*CommentsTreeResp)(nil), "action.CommentsTreeResp")
}

func init() { proto.RegisterFile("action.proto", fileDescriptor_59885c909ad4dfd3) }

var fileDescriptor_59885c909ad4dfd3 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0xe0, 0xba, 0x93, 0x86, 0x96, 0x2d, 0x04, 0xcb, 0x50, 0x54, 0x59, 0x1c, 0x72,
	0x2a, 0x52, 0xa0, 0x37, 0x2e, 0x49, 0x90, 0x2c, 0xf7, 0x10, 0x55, 0x4b, 0x7a, 0xe1, 0xe6, 0xc6,
	0xd3, 0x62, 0x25, 0xf6, 0x3a, 0xde, 0xcd, 0xa1, 0x47, 0x04, 0xbf, 0xc5, 0x1f, 0xc0, 0x3f, 0x21,
	0xef, 0xae, 0x1d, 0xc7, 0x6e, 0x2b, 0x2a, 0x21, 0xa4, 0xde, 0x3c, 0x33, 0x6f, 0x9e, 0xe7, 0xed,
	0xcc, 0xec, 0xc2, 0x5e, 0x30, 0x17, 0x11, 0x4b, 0x4e, 0xd2, 0x8c, 0x09, 0x46, 0x4c, 0x65, 0xb9,
	0x47, 0xb0, 0x43, 0x71, 0xb5, 0x46, 0x2e, 0x08, 0x81, 0x4e, 0x1a, 0x25, 0xd7, 0xb6, 0x71, 0x6c,
	0x0c, 0x76, 0xa9, 0xfc, 0x76, 0x3f, 0x80, 0x45, 0x91, 0xa7, 0x2c, 0xe1, 0x48, 0x9e, 0x42, 0x8b,
	0x2d, 0x64, 0xd4, 0xa2, 0x2d, 0xb6, 0x20, 0x36, 0xec, 0xc4, 0xc8, 0x79, 0x70, 0x8d, 0x76, 0x4b,
	0xa6, 0x14, 0xa6, 0xfb, 0xdd, 0x80, 0xc3, 0x59, 0x16, 0x5c, 0x5d, 0x45, 0xf3, 0xcf, 0x22, 0x10,
	0x11, 0x17, 0xd1, 0x9c, 0xe2, 0x2a, 0x67, 0x88, 0x42, 0xc9, 0xd0, 0xa6, 0xad, 0x28, 0x24, 0x7d,
	0x30, 0xc7, 0x8c, 0x2d, 0xfc, 0x50, 0x12, 0xb4, 0xa9, 0xb6, 0xc8, 0x1b, 0x80, 0xc9, 0xd7, 0x20,
	0x15, 0x98, 0x4d, 0xd7, 0xb1, 0xdd, 0x96, 0xb1, 0x8a, 0x87, 0xbc, 0x85, 0x9e, 0xa6, 0x9f, 0xae,
	0xe3, 0x4b, 0xcc, 0xec, 0x8e, 0x84, 0x6c, 0x3b, 0xdd, 0x1f, 0x06, 0x3c, 0x6f, 0x56, 0xc1, 0xd3,
	0xff, 0x5c, 0xc6, 0x1c, 0x5e, 0xd4, 0xab, 0xe0, 0xb2, 0x8c, 0x33, 0x78, 0xd6, 0x08, 0xd8, 0xc6,
	0x71, 0x7b, 0xd0, 0x1d, 0xbe, 0x3e, 0xd1, 0xcd, 0xba, 0xad, 0x7e, 0xda, 0x4c, 0x73, 0x7f, 0x19,
	0x00, 0x13, 0x16, 0xc7, 0x98, 0x08, 0x7d, 0xd0, 0x7e, 0xa9, 0xd0, 0x0f, 0x89, 0x03, 0xd6, 0x79,
	0x90, 0x61, 0x22, 0x4a, 0x8d, 0xa5, 0x9d, 0xab, 0xc8, 0xf5, 0x4e, 0x58, 0x22, 0x14, 0x40, 0x09,
	0xdd, 0x76, 0xe6, 0xcd, 0xd6, 0xfc, 0x52, 0xe5, 0x2e, 0x2d, 0x4c, 0x32, 0x80, 0x7d, 0xfd, 0x39,
	0xbe, 0xb9, 0xe0, 0x98, 0xf9, 0xa1, 0xfd, 0x44, 0x32, 0xd4, 0xdd, 0x15, 0xe4, 0x8c, 0x69, 0xa4,
	0xb9, 0x85, 0x2c, 0xdc, 0xee, 0x6f, 0x03, 0xba, 0xa5, 0x1c, 0xd5, 0xb1, 0x47, 0xad, 0xe7, 0x9b,
	0x01, 0x07, 0xda, 0xc7, 0xa7, 0x2c, 0x44, 0x29, 0xea, 0x1d, 0x58, 0x85, 0x4f, 0x4a, 0xeb, 0x0e,
	0x0f, 0x8b, 0xb6, 0x57, 0xb4, 0xd3, 0x12, 0x44, 0x3e, 0xc2, 0x5e, 0x95, 0xc4, 0x6e, 0xc9, 0x59,
	0xb1, 0x6b, 0x49, 0xe5, 0x0f, 0xe8, 0x16, 0xda, 0x3d, 0xdf, 0x94, 0x30, 0xcb, 0x50, 0x95, 0x50,
	0x61, 0xcc, 0x7d, 0x7a, 0xfa, 0xfe, 0x82, 0x31, 0x47, 0x0f, 0x7f, 0x76, 0xc0, 0x1c, 0x49, 0x24,
	0xf1, 0xe1, 0xa5, 0x87, 0x62, 0xb4, 0x5c, 0x36, 0x46, 0x93, 0xec, 0x17, 0x6c, 0xfa, 0x9e, 0x71,
	0x8e, 0xee, 0x1a, 0x6e, 0xb5, 0x16, 0x08, 0x03, 0x0f, 0x45, 0x3d, 0x36, 0xbe, 0x51, 0x4b, 0x39,
	0x4a, 0xc2, 0xca, 0x06, 0xbe, 0xba, 0x7b, 0x4f, 0x56, 0xce, 0xbd, 0x4b, 0x44, 0x3c, 0xe8, 0x4f,
	0x32, 0x0c, 0x04, 0xd6, 0xa3, 0xf7, 0x93, 0x1e, 0x6c, 0xd4, 0xe8, 0x6b, 0xd1, 0x83, 0xfe, 0x45,
	0x1a, 0xfe, 0x03, 0xa2, 0x33, 0x70, 0x3c, 0x14, 0xc5, 0x09, 0x2b, 0xc1, 0x9b, 0x81, 0x25, 0x8d,
	0xd9, 0x58, 0x39, 0x8d, 0x46, 0x95, 0x8d, 0x3d, 0x85, 0x9e, 0x52, 0x57, 0x4c, 0xf5, 0x6d, 0xe9,
	0xcd, 0x12, 0x4e, 0xa1, 0xa7, 0xb4, 0x3c, 0x38, 0xed, 0x13, 0x2e, 0xf1, 0x81, 0x69, 0x63, 0xeb,
	0x8b, 0x7e, 0x85, 0x2e, 0x4d, 0xf9, 0x28, 0xbd, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa8,
	0xb9, 0x5f, 0xa4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActionClient is the client API for Action service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActionClient interface {
	//TrafficStatistic
	GetAllTrafficStatistics(ctx context.Context, in *Request, opts ...grpc.CallOption) (*TrafficStatisticsResp, error)
	GetTrafficStatisticByBookIdAndChapterNum(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*TrafficStatisticResp, error)
	CreateTrafficStatistic(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*Response, error)
	UpdateTrafficStatistic(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*Response, error)
	//Comments
	GetCommentsByBookContentId(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentsTreeResp, error)
	CreateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error)
	UpdateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error)
	DeleteComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error)
}

type actionClient struct {
	cc *grpc.ClientConn
}

func NewActionClient(cc *grpc.ClientConn) ActionClient {
	return &actionClient{cc}
}

func (c *actionClient) GetAllTrafficStatistics(ctx context.Context, in *Request, opts ...grpc.CallOption) (*TrafficStatisticsResp, error) {
	out := new(TrafficStatisticsResp)
	err := c.cc.Invoke(ctx, "/action.Action/GetAllTrafficStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) GetTrafficStatisticByBookIdAndChapterNum(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*TrafficStatisticResp, error) {
	out := new(TrafficStatisticResp)
	err := c.cc.Invoke(ctx, "/action.Action/GetTrafficStatisticByBookIdAndChapterNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) CreateTrafficStatistic(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/action.Action/CreateTrafficStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) UpdateTrafficStatistic(ctx context.Context, in *TrafficStatisticReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/action.Action/UpdateTrafficStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) GetCommentsByBookContentId(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentsTreeResp, error) {
	out := new(CommentsTreeResp)
	err := c.cc.Invoke(ctx, "/action.Action/GetCommentsByBookContentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) CreateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/action.Action/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) UpdateComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/action.Action/UpdateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) DeleteComment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/action.Action/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionServer is the server API for Action service.
type ActionServer interface {
	//TrafficStatistic
	GetAllTrafficStatistics(context.Context, *Request) (*TrafficStatisticsResp, error)
	GetTrafficStatisticByBookIdAndChapterNum(context.Context, *TrafficStatisticReq) (*TrafficStatisticResp, error)
	CreateTrafficStatistic(context.Context, *TrafficStatisticReq) (*Response, error)
	UpdateTrafficStatistic(context.Context, *TrafficStatisticReq) (*Response, error)
	//Comments
	GetCommentsByBookContentId(context.Context, *CommentReq) (*CommentsTreeResp, error)
	CreateComment(context.Context, *CommentReq) (*Response, error)
	UpdateComment(context.Context, *CommentReq) (*Response, error)
	DeleteComment(context.Context, *CommentReq) (*Response, error)
}

// UnimplementedActionServer can be embedded to have forward compatible implementations.
type UnimplementedActionServer struct {
}

func (*UnimplementedActionServer) GetAllTrafficStatistics(ctx context.Context, req *Request) (*TrafficStatisticsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTrafficStatistics not implemented")
}
func (*UnimplementedActionServer) GetTrafficStatisticByBookIdAndChapterNum(ctx context.Context, req *TrafficStatisticReq) (*TrafficStatisticResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrafficStatisticByBookIdAndChapterNum not implemented")
}
func (*UnimplementedActionServer) CreateTrafficStatistic(ctx context.Context, req *TrafficStatisticReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrafficStatistic not implemented")
}
func (*UnimplementedActionServer) UpdateTrafficStatistic(ctx context.Context, req *TrafficStatisticReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrafficStatistic not implemented")
}
func (*UnimplementedActionServer) GetCommentsByBookContentId(ctx context.Context, req *CommentReq) (*CommentsTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByBookContentId not implemented")
}
func (*UnimplementedActionServer) CreateComment(ctx context.Context, req *CommentReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedActionServer) UpdateComment(ctx context.Context, req *CommentReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (*UnimplementedActionServer) DeleteComment(ctx context.Context, req *CommentReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}

func RegisterActionServer(s *grpc.Server, srv ActionServer) {
	s.RegisterService(&_Action_serviceDesc, srv)
}

func _Action_GetAllTrafficStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).GetAllTrafficStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/GetAllTrafficStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).GetAllTrafficStatistics(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_GetTrafficStatisticByBookIdAndChapterNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficStatisticReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).GetTrafficStatisticByBookIdAndChapterNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/GetTrafficStatisticByBookIdAndChapterNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).GetTrafficStatisticByBookIdAndChapterNum(ctx, req.(*TrafficStatisticReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_CreateTrafficStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficStatisticReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).CreateTrafficStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/CreateTrafficStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).CreateTrafficStatistic(ctx, req.(*TrafficStatisticReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_UpdateTrafficStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficStatisticReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).UpdateTrafficStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/UpdateTrafficStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).UpdateTrafficStatistic(ctx, req.(*TrafficStatisticReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_GetCommentsByBookContentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).GetCommentsByBookContentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/GetCommentsByBookContentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).GetCommentsByBookContentId(ctx, req.(*CommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).CreateComment(ctx, req.(*CommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).UpdateComment(ctx, req.(*CommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).DeleteComment(ctx, req.(*CommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Action_serviceDesc = grpc.ServiceDesc{
	ServiceName: "action.Action",
	HandlerType: (*ActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTrafficStatistics",
			Handler:    _Action_GetAllTrafficStatistics_Handler,
		},
		{
			MethodName: "GetTrafficStatisticByBookIdAndChapterNum",
			Handler:    _Action_GetTrafficStatisticByBookIdAndChapterNum_Handler,
		},
		{
			MethodName: "CreateTrafficStatistic",
			Handler:    _Action_CreateTrafficStatistic_Handler,
		},
		{
			MethodName: "UpdateTrafficStatistic",
			Handler:    _Action_UpdateTrafficStatistic_Handler,
		},
		{
			MethodName: "GetCommentsByBookContentId",
			Handler:    _Action_GetCommentsByBookContentId_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Action_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _Action_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Action_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "action.proto",
}
