// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type OrderGoods struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNum             string   `protobuf:"bytes,2,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	BookId               int64    `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderGoods) Reset()         { *m = OrderGoods{} }
func (m *OrderGoods) String() string { return proto.CompactTextString(m) }
func (*OrderGoods) ProtoMessage()    {}
func (*OrderGoods) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *OrderGoods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderGoods.Unmarshal(m, b)
}
func (m *OrderGoods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderGoods.Marshal(b, m, deterministic)
}
func (m *OrderGoods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderGoods.Merge(m, src)
}
func (m *OrderGoods) XXX_Size() int {
	return xxx_messageInfo_OrderGoods.Size(m)
}
func (m *OrderGoods) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderGoods.DiscardUnknown(m)
}

var xxx_messageInfo_OrderGoods proto.InternalMessageInfo

func (m *OrderGoods) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderGoods) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *OrderGoods) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *OrderGoods) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type OrderInfoReq struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId              int64         `protobuf:"varint,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	OrderNum             string        `protobuf:"bytes,3,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	CreateTime           string        `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Cost                 int64         `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	IsPaid               bool          `protobuf:"varint,6,opt,name=isPaid,proto3" json:"isPaid,omitempty"`
	OrderStatus          string        `protobuf:"bytes,7,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	Goods                []*OrderGoods `protobuf:"bytes,8,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderInfoReq) Reset()         { *m = OrderInfoReq{} }
func (m *OrderInfoReq) String() string { return proto.CompactTextString(m) }
func (*OrderInfoReq) ProtoMessage()    {}
func (*OrderInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *OrderInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoReq.Unmarshal(m, b)
}
func (m *OrderInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoReq.Marshal(b, m, deterministic)
}
func (m *OrderInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoReq.Merge(m, src)
}
func (m *OrderInfoReq) XXX_Size() int {
	return xxx_messageInfo_OrderInfoReq.Size(m)
}
func (m *OrderInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoReq proto.InternalMessageInfo

func (m *OrderInfoReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfoReq) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *OrderInfoReq) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *OrderInfoReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *OrderInfoReq) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *OrderInfoReq) GetIsPaid() bool {
	if m != nil {
		return m.IsPaid
	}
	return false
}

func (m *OrderInfoReq) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *OrderInfoReq) GetGoods() []*OrderGoods {
	if m != nil {
		return m.Goods
	}
	return nil
}

type OrderInfoResp struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId              int64         `protobuf:"varint,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	OrderNum             string        `protobuf:"bytes,3,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	CreateTime           string        `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Cost                 int64         `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	IsPaid               bool          `protobuf:"varint,6,opt,name=isPaid,proto3" json:"isPaid,omitempty"`
	OrderStatus          string        `protobuf:"bytes,7,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	Goods                []*OrderGoods `protobuf:"bytes,8,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderInfoResp) Reset()         { *m = OrderInfoResp{} }
func (m *OrderInfoResp) String() string { return proto.CompactTextString(m) }
func (*OrderInfoResp) ProtoMessage()    {}
func (*OrderInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *OrderInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoResp.Unmarshal(m, b)
}
func (m *OrderInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoResp.Marshal(b, m, deterministic)
}
func (m *OrderInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoResp.Merge(m, src)
}
func (m *OrderInfoResp) XXX_Size() int {
	return xxx_messageInfo_OrderInfoResp.Size(m)
}
func (m *OrderInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoResp proto.InternalMessageInfo

func (m *OrderInfoResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfoResp) GetBuyerId() int64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *OrderInfoResp) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *OrderInfoResp) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *OrderInfoResp) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *OrderInfoResp) GetIsPaid() bool {
	if m != nil {
		return m.IsPaid
	}
	return false
}

func (m *OrderInfoResp) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *OrderInfoResp) GetGoods() []*OrderGoods {
	if m != nil {
		return m.Goods
	}
	return nil
}

type OrderInfosResp struct {
	OrderInfos           []*OrderInfoResp `protobuf:"bytes,1,rep,name=OrderInfos,proto3" json:"OrderInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderInfosResp) Reset()         { *m = OrderInfosResp{} }
func (m *OrderInfosResp) String() string { return proto.CompactTextString(m) }
func (*OrderInfosResp) ProtoMessage()    {}
func (*OrderInfosResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *OrderInfosResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfosResp.Unmarshal(m, b)
}
func (m *OrderInfosResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfosResp.Marshal(b, m, deterministic)
}
func (m *OrderInfosResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfosResp.Merge(m, src)
}
func (m *OrderInfosResp) XXX_Size() int {
	return xxx_messageInfo_OrderInfosResp.Size(m)
}
func (m *OrderInfosResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfosResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfosResp proto.InternalMessageInfo

func (m *OrderInfosResp) GetOrderInfos() []*OrderInfoResp {
	if m != nil {
		return m.OrderInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "order.Request")
	proto.RegisterType((*Response)(nil), "order.Response")
	proto.RegisterType((*OrderGoods)(nil), "order.OrderGoods")
	proto.RegisterType((*OrderInfoReq)(nil), "order.OrderInfoReq")
	proto.RegisterType((*OrderInfoResp)(nil), "order.OrderInfoResp")
	proto.RegisterType((*OrderInfosResp)(nil), "order.OrderInfosResp")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x4d, 0x5b, 0x4a, 0xcb, 0xe5, 0x3d, 0xc8, 0x9b, 0x47, 0xc8, 0x84, 0x44, 0x43, 0xba, 0x91,
	0x15, 0x0b, 0x24, 0x61, 0x0f, 0x51, 0xc2, 0x46, 0xcc, 0xa8, 0x1b, 0x77, 0x85, 0x19, 0x48, 0x43,
	0xe8, 0x94, 0xce, 0x74, 0xc1, 0x0f, 0xf0, 0xd7, 0xea, 0x8f, 0x30, 0xbd, 0xfd, 0xb0, 0x0a, 0x1b,
	0x5d, 0xba, 0x9b, 0x73, 0xee, 0x9c, 0x73, 0xef, 0x3d, 0x30, 0x85, 0xa6, 0x8c, 0xb9, 0x88, 0x87,
	0x51, 0x2c, 0xb5, 0x24, 0x36, 0x02, 0xef, 0x02, 0x1c, 0x26, 0x0e, 0x89, 0x50, 0x9a, 0x10, 0xa8,
	0x45, 0x41, 0xb8, 0xa5, 0x46, 0xdf, 0x18, 0x34, 0x18, 0x9e, 0xbd, 0x31, 0xb8, 0x4c, 0xa8, 0x48,
	0x86, 0x4a, 0x90, 0x16, 0x98, 0x72, 0x87, 0x55, 0x97, 0x99, 0x72, 0x47, 0x28, 0x38, 0x7b, 0xa1,
	0x94, 0xbf, 0x15, 0xd4, 0x44, 0x49, 0x01, 0xbd, 0x0d, 0xc0, 0x32, 0x75, 0x9f, 0x4b, 0xc9, 0x55,
	0xaa, 0x0b, 0x38, 0xea, 0x2c, 0x66, 0x06, 0x9c, 0xf4, 0xc0, 0xc5, 0xde, 0x77, 0xc9, 0x3e, 0x17,
	0x96, 0x98, 0x74, 0xa1, 0xbe, 0x92, 0x72, 0xb7, 0xe0, 0xd4, 0xc2, 0xfb, 0x39, 0x22, 0x1d, 0xb0,
	0x67, 0x32, 0x09, 0x35, 0xad, 0x21, 0x9d, 0x01, 0xef, 0xd5, 0x80, 0x3f, 0xd8, 0x68, 0x11, 0x6e,
	0x24, 0x13, 0x87, 0x93, 0x56, 0x14, 0x9c, 0x55, 0x72, 0x14, 0xf1, 0x82, 0x63, 0x27, 0x8b, 0x15,
	0xf0, 0xd3, 0x10, 0xd6, 0x97, 0x21, 0x2e, 0x01, 0xd6, 0xb1, 0xf0, 0xb5, 0x78, 0x0c, 0xf6, 0x02,
	0x3b, 0x36, 0x58, 0x85, 0x49, 0x83, 0x5a, 0x4b, 0xa5, 0xa9, 0x8d, 0x96, 0x78, 0x4e, 0x07, 0x0f,
	0xd4, 0xbd, 0x1f, 0x70, 0x5a, 0xc7, 0x80, 0x72, 0x44, 0xfa, 0x79, 0xea, 0x0f, 0xda, 0xd7, 0x89,
	0xa2, 0x0e, 0x9a, 0x55, 0x29, 0x72, 0x05, 0xf6, 0x36, 0xcd, 0x89, 0xba, 0x7d, 0x6b, 0xd0, 0x1c,
	0xfd, 0x1b, 0x66, 0xbf, 0xd2, 0x47, 0x80, 0x2c, 0xab, 0x7b, 0x6f, 0x06, 0xfc, 0xad, 0x6c, 0xab,
	0xa2, 0xdf, 0xbd, 0xee, 0x2d, 0xb4, 0xca, 0x6d, 0x15, 0xae, 0x3b, 0xce, 0xff, 0x56, 0xc8, 0x50,
	0x03, 0xf5, 0x9d, 0xaa, 0xbe, 0x08, 0x86, 0x55, 0xee, 0x8d, 0x5e, 0x4c, 0xb0, 0x11, 0x92, 0x19,
	0x74, 0xe7, 0x42, 0x97, 0xa5, 0xe9, 0x71, 0x59, 0x44, 0xf0, 0xff, 0xd4, 0xe5, 0xd0, 0x3b, 0x6b,
	0x4d, 0x6e, 0x80, 0x16, 0x26, 0xd9, 0x46, 0x3f, 0xb3, 0x99, 0x40, 0x7b, 0x86, 0x11, 0x97, 0xf4,
	0x79, 0x75, 0x3b, 0x27, 0xcb, 0x57, 0x38, 0x81, 0xf6, 0x53, 0xc4, 0xbf, 0x2f, 0x9c, 0x3a, 0xcf,
	0xd9, 0x93, 0x5f, 0xd5, 0xf1, 0x03, 0x70, 0xfd, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9d, 0x4a,
	0x6f, 0x0f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	GetOrderInfoByOrderNum(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error)
	GetOrderStatusByOrderNum(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error)
	CreateOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*Response, error)
	UpdateOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*Response, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) GetOrderInfoByOrderNum(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error) {
	out := new(OrderInfoResp)
	err := c.cc.Invoke(ctx, "/order.Order/GetOrderInfoByOrderNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderStatusByOrderNum(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error) {
	out := new(OrderInfoResp)
	err := c.cc.Invoke(ctx, "/order.Order/GetOrderStatusByOrderNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/order.Order/UpdateOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	GetOrderInfoByOrderNum(context.Context, *OrderInfoReq) (*OrderInfoResp, error)
	GetOrderStatusByOrderNum(context.Context, *OrderInfoReq) (*OrderInfoResp, error)
	CreateOrderInfo(context.Context, *OrderInfoReq) (*Response, error)
	UpdateOrderInfo(context.Context, *OrderInfoReq) (*Response, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) GetOrderInfoByOrderNum(ctx context.Context, req *OrderInfoReq) (*OrderInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfoByOrderNum not implemented")
}
func (*UnimplementedOrderServer) GetOrderStatusByOrderNum(ctx context.Context, req *OrderInfoReq) (*OrderInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderStatusByOrderNum not implemented")
}
func (*UnimplementedOrderServer) CreateOrderInfo(ctx context.Context, req *OrderInfoReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderInfo not implemented")
}
func (*UnimplementedOrderServer) UpdateOrderInfo(ctx context.Context, req *OrderInfoReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderInfo not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_GetOrderInfoByOrderNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderInfoByOrderNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetOrderInfoByOrderNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderInfoByOrderNum(ctx, req.(*OrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderStatusByOrderNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderStatusByOrderNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetOrderStatusByOrderNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderStatusByOrderNum(ctx, req.(*OrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrderInfo(ctx, req.(*OrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/UpdateOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateOrderInfo(ctx, req.(*OrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderInfoByOrderNum",
			Handler:    _Order_GetOrderInfoByOrderNum_Handler,
		},
		{
			MethodName: "GetOrderStatusByOrderNum",
			Handler:    _Order_GetOrderStatusByOrderNum_Handler,
		},
		{
			MethodName: "CreateOrderInfo",
			Handler:    _Order_CreateOrderInfo_Handler,
		},
		{
			MethodName: "UpdateOrderInfo",
			Handler:    _Order_UpdateOrderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
