// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package bookclient

import (
	"context"

	"Book/book"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BookBasicInfoReply  = book.BookBasicInfoReply
	BookBasicInfoReq    = book.BookBasicInfoReq
	BookContentReply    = book.BookContentReply
	BookContentReq      = book.BookContentReq
	BookContentsReply   = book.BookContentsReply
	BookInventoryReq    = book.BookInventoryReq
	BookInventoryResp   = book.BookInventoryResp
	BooksBasicInfoReply = book.BooksBasicInfoReply
	BooksInventoryResp  = book.BooksInventoryResp
	Reply               = book.Reply
	Request             = book.Request
	UsernameReq         = book.UsernameReq

	Book interface {
		//   book_basic_info
		FindAllBooksSortedByMonth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
		FindAllBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
		FindBooksByLikeName(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
		FindBooksByStorageUserId(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error)
		FindOneBookById(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BookBasicInfoReply, error)
		CreateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
		DeleteBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
		UpdateUser(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error)
		//   book_content
		FindAllBookContentsByBookId(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentsReply, error)
		FindOneBookContentByBookIdAndChapterNum(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentReply, error)
		CreateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
		DeleteBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
		UpdateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error)
		//  book_inventory
		FindAllBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BooksInventoryResp, error)
		FindBookInventoryByBookId(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BookInventoryResp, error)
		CreateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error)
		UpdateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error)
	}

	defaultBook struct {
		cli zrpc.Client
	}
)

func NewBook(cli zrpc.Client) Book {
	return &defaultBook{
		cli: cli,
	}
}

//   book_basic_info
func (m *defaultBook) FindAllBooksSortedByMonth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindAllBooksSortedByMonth(ctx, in, opts...)
}

func (m *defaultBook) FindAllBooks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindAllBooks(ctx, in, opts...)
}

func (m *defaultBook) FindBooksByLikeName(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindBooksByLikeName(ctx, in, opts...)
}

func (m *defaultBook) FindBooksByStorageUserId(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BooksBasicInfoReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindBooksByStorageUserId(ctx, in, opts...)
}

func (m *defaultBook) FindOneBookById(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*BookBasicInfoReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindOneBookById(ctx, in, opts...)
}

func (m *defaultBook) CreateBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.CreateBook(ctx, in, opts...)
}

func (m *defaultBook) DeleteBook(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.DeleteBook(ctx, in, opts...)
}

func (m *defaultBook) UpdateUser(ctx context.Context, in *BookBasicInfoReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

//   book_content
func (m *defaultBook) FindAllBookContentsByBookId(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentsReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindAllBookContentsByBookId(ctx, in, opts...)
}

func (m *defaultBook) FindOneBookContentByBookIdAndChapterNum(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*BookContentReply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindOneBookContentByBookIdAndChapterNum(ctx, in, opts...)
}

func (m *defaultBook) CreateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.CreateBookContent(ctx, in, opts...)
}

func (m *defaultBook) DeleteBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.DeleteBookContent(ctx, in, opts...)
}

func (m *defaultBook) UpdateBookContent(ctx context.Context, in *BookContentReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.UpdateBookContent(ctx, in, opts...)
}

//  book_inventory
func (m *defaultBook) FindAllBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BooksInventoryResp, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindAllBookInventory(ctx, in, opts...)
}

func (m *defaultBook) FindBookInventoryByBookId(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*BookInventoryResp, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.FindBookInventoryByBookId(ctx, in, opts...)
}

func (m *defaultBook) CreateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.CreateBookInventory(ctx, in, opts...)
}

func (m *defaultBook) UpdateBookInventory(ctx context.Context, in *BookInventoryReq, opts ...grpc.CallOption) (*Reply, error) {
	client := book.NewBookClient(m.cli.Conn())
	return client.UpdateBookInventory(ctx, in, opts...)
}
